#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor DP-2 -d I II III IV V 
bspc monitor DP-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a LibreOffice desktop='^2' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a brave desktop='^2'
bspc rule -a Steam desktop='^7'
bspc rule -a discord desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Plank layer=above manage=on border=off
bspc rule -a Plank state=floating layer=below manage=off border=off

wmname LG3D


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

#Bars
#plank &
#tint2 &
# Bar
~/.config/bspwm/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
#picom -CGb &
picom --config ~/.config/bspwm/picom/picom.conf --experimental-backends &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#autostart programs
~/.config/bspwm/scripts/autostart.sh
